### ISSUE TITLE
can I draw whole genome coverage from nucplot

### ISSUE THREAD

**Issue by zhoudreames** [mrvollger/NucFreq#3]
I want to draw the whole genome coverage plot using your software nucplot,Can this function be realized? thanks~

**Comment by mrvollger** [comment]
The answer is probably no. Many genomes are millions to billions of bases and plotting that many points with any software onto a static image is not useful/feasible. 

If you really need the whole genome I recommend running many jobs with sliding windows across the genome and combing those plots into some kind of PDF booklet. 

If your genome is small (chromosomes less than a few million bases) NucFreq should be able to plot whole genome with no additional changes to the code.

**Comment by zhoudreames** [comment]
thanks~
